# Generated by Django 5.2.6 on 2025-09-30 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('short_description', models.CharField(max_length=300, verbose_name='Description courte')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('badge', models.CharField(max_length=50, verbose_name='Badge')),
                ('level', models.CharField(choices=[('initiation', 'Initiation'), ('basic', 'Basique'), ('advanced', 'Avancé'), ('elite', 'Élite')], max_length=20, verbose_name='Niveau')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=20, verbose_name='Statut')),
                ('features', models.JSONField(default=list, verbose_name='Fonctionnalités')),
                ('learnings', models.JSONField(default=list, verbose_name="Objectifs d'apprentissage")),
                ('duration', models.CharField(max_length=50, verbose_name='Durée')),
                ('lessons_count', models.PositiveIntegerField(default=0, verbose_name='Nombre de leçons')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'étudiants")),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='Note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('meta_title', models.CharField(blank=True, max_length=200, verbose_name='Meta titre')),
                ('meta_description', models.TextField(blank=True, verbose_name='Meta description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_formations', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GestionCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('account_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde du compte')),
                ('risk_profile', models.CharField(choices=[('conservative', 'Conservateur'), ('moderate', 'Modéré'), ('aggressive', 'Agressif')], max_length=20, verbose_name='Profil de risque')),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Drawdown maximum (%)')),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde initial')),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Solde actuel')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Profit total')),
                ('total_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Perte totale')),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Profit (%)')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('paused', 'En pause'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('managed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_accounts', to=settings.AUTH_USER_MODEL, verbose_name='Géré par')),
            ],
            options={
                'verbose_name': 'Gestion de Compte',
                'verbose_name_plural': 'Gestion de Comptes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20, verbose_name='Paire de devises')),
                ('signal_type', models.CharField(choices=[('buy', 'Achat'), ('sell', 'Vente')], max_length=10, verbose_name='Type de signal')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Statut')),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=10, verbose_name="Prix d'entrée")),
                ('target_price', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Prix cible')),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Stop Loss')),
                ('risk_level', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], max_length=10, verbose_name='Niveau de risque')),
                ('timeframe', models.CharField(choices=[('M1', '1 Minute'), ('M5', '5 Minutes'), ('M15', '15 Minutes'), ('M30', '30 Minutes'), ('H1', '1 Heure'), ('H4', '4 Heures'), ('D1', '1 Jour'), ('W1', '1 Semaine')], max_length=10, verbose_name='Timeframe')),
                ('actual_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Profit réel')),
                ('actual_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Perte réelle')),
                ('pips_result', models.CharField(blank=True, max_length=20, verbose_name='Résultat en pips')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('analysis', models.TextField(blank=True, verbose_name='Analyse technique')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_signals', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Signal',
                'verbose_name_plural': 'Signaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('formations', 'Formations'), ('signaux', 'Signaux'), ('gestion', 'Gestion de Comptes'), ('general', 'Général')], max_length=20, verbose_name='Type de service')),
                ('section', models.CharField(max_length=100, verbose_name='Section')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_content', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Contenu de Service',
                'verbose_name_plural': 'Contenus de Services',
                'ordering': ['service_type', 'order'],
                'unique_together': {('service_type', 'section')},
            },
        ),
    ]
