# Generated by Django 5.2.6 on 2025-09-30 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_formation_gestioncompte_signal_servicecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestioncompte',
            name='managed_by',
        ),
        migrations.AlterUniqueTogether(
            name='servicecontent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicecontent',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='Formation',
        ),
        migrations.DeleteModel(
            name='GestionCompte',
        ),
        migrations.DeleteModel(
            name='ServiceContent',
        ),
        migrations.DeleteModel(
            name='Signal',
        ),
    ]
