# Generated by Django 5.2.6 on 2025-10-07 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone_alter_user_telegram_username'),
        ('payments', '0003_offer_color_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_make_payment',
            field=models.BooleanField(default=False, help_text="L'utilisateur peut effectuer un paiement"),
        ),
        migrations.AddField(
            model_name='user',
            name='discord_username',
            field=models.CharField(blank=True, help_text='Username#1234 Discord (obligatoire pour recevoir les signaux)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Numéro WhatsApp (facultatif, format: +33612345678)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, help_text='@username Telegram (obligatoire pour recevoir les signaux)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('subscription_expiring', 'Abonnement expirant'), ('subscription_expired', 'Abonnement expiré'), ('payment_received', 'Paiement reçu'), ('payment_pending', 'Paiement en attente'), ('profile_incomplete', 'Profil incomplet'), ('welcome', 'Bienvenue'), ('general', 'Général')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('read', 'Lu'), ('dismissed', 'Ignoré')], default='pending', max_length=20)),
                ('scheduled_for', models.DateTimeField(blank=True, help_text='Quand envoyer la notification', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payments.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification utilisateur',
                'verbose_name_plural': 'Notifications utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_us_user_id_71287c_idx'), models.Index(fields=['scheduled_for'], name='accounts_us_schedul_a5af59_idx')],
            },
        ),
    ]
