# Generated by Django 5.2.6 on 2025-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_formations_admin_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Utilisateur'), ('customer_service', 'Service Client'), ('admin', 'Administrateur')], default='user', help_text="Rôle de l'utilisateur dans le système", max_length=20),
        ),
    ]
