# Generated by Django 5.2.6 on 2025-10-09 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='Numéro de facture')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=15, verbose_name='Statut')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Payé le')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Méthode de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Facture Support',
                'verbose_name_plural': 'Factures Support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.supportinvoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Article Facture',
                'verbose_name_plural': 'Articles Facture',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priorité')),
                ('status', models.CharField(choices=[('unread', 'Non lu'), ('read', 'Lu'), ('replied', 'Répondu'), ('closed', 'Fermé')], default='unread', max_length=10, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Message Support',
                'verbose_name_plural': 'Messages Support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_name', models.CharField(max_length=200, verbose_name="Nom de l'offre")),
                ('offer_description', models.TextField(verbose_name="Description de l'offre")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='pending', max_length=15, verbose_name='Statut')),
                ('payment_status', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échec'), ('refunded', 'Remboursé')], default='pending', max_length=15, verbose_name='Statut de paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('tracking_info', models.JSONField(blank=True, default=dict, verbose_name='Informations de suivi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande Support',
                'verbose_name_plural': 'Commandes Support',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_text', models.TextField(verbose_name='Réponse')),
                ('is_from_support', models.BooleanField(default=True, verbose_name='De la part du support')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='accounts.supportmessage', verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Réponse Support',
                'verbose_name_plural': 'Réponses Support',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('category', models.CharField(choices=[('technical', 'Technique'), ('billing', 'Facturation'), ('general', 'Général'), ('feature_request', 'Demande de fonctionnalité')], default='general', max_length=20, verbose_name='Catégorie')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_progress', 'En cours'), ('resolved', 'Résolu'), ('closed', 'Fermé')], default='open', max_length=15, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priorité')),
                ('description', models.TextField(verbose_name='Description')),
                ('resolution', models.TextField(blank=True, verbose_name='Résolution')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Ticket Support',
                'verbose_name_plural': 'Tickets Support',
                'ordering': ['-created_at'],
            },
        ),
    ]
