# Generated by Django 5.2.6 on 2025-09-30 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(max_length=100, verbose_name='Clé de section')),
                ('content_type', models.CharField(choices=[('text', 'Texte'), ('heading', 'Titre'), ('image', 'Image'), ('button', 'Bouton'), ('card', 'Carte'), ('list', 'Liste'), ('hero', 'Section Hero'), ('pricing', 'Tarifs'), ('testimonial', 'Témoignage'), ('feature', 'Fonctionnalité'), ('stats', 'Statistiques')], max_length=20, verbose_name='Type de contenu')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Éditable')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Section de Contenu',
                'verbose_name_plural': 'Sections de Contenu',
                'ordering': ['page', 'order', 'section_key'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la page')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la page')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdminPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Hash du mot de passe')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_passwords', to=settings.AUTH_USER_MODEL, verbose_name='Mis à jour par')),
            ],
            options={
                'verbose_name': 'Mot de Passe Admin',
                'verbose_name_plural': 'Mots de Passe Admin',
            },
        ),
        migrations.CreateModel(
            name='ContentEditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Démarrée le')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Dernière activité')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_sessions', to='content.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': "Session d'Édition",
                'verbose_name_plural': "Sessions d'Édition",
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ContentChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='Nom du champ')),
                ('old_value', models.TextField(blank=True, verbose_name='Ancienne valeur')),
                ('new_value', models.TextField(blank=True, verbose_name='Nouvelle valeur')),
                ('change_type', models.CharField(choices=[('update', 'Mise à jour'), ('create', 'Création'), ('delete', 'Suppression')], max_length=20, verbose_name='Type de changement')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='content.contenteditsession', verbose_name='Session')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_changes', to='content.contentsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Changement de Contenu',
                'verbose_name_plural': 'Changements de Contenu',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contentsection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='content.page', verbose_name='Page'),
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('content', models.TextField(blank=True, verbose_name='Contenu')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('version_number', models.PositiveIntegerField(verbose_name='Numéro de version')),
                ('change_summary', models.CharField(blank=True, max_length=500, verbose_name='Résumé des changements')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_versions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='content.contentsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Version de Contenu',
                'verbose_name_plural': 'Versions de Contenu',
                'ordering': ['-created_at'],
                'unique_together': {('section', 'version_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contentsection',
            unique_together={('page', 'section_key')},
        ),
    ]
