# Generated by Django 5.2.6 on 2025-09-30 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentsection_page_adminpassword_contenteditsession_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=50, verbose_name='Nom du champ')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English'), ('es', 'Español')], max_length=5, verbose_name='Langue')),
                ('translated_content', models.TextField(verbose_name='Contenu traduit')),
                ('is_auto_generated', models.BooleanField(default=True, verbose_name='Généré automatiquement')),
                ('is_manual_override', models.BooleanField(default=False, verbose_name='Modification manuelle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.contentsection', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Traduction',
                'verbose_name_plural': 'Traductions',
                'ordering': ['section', 'language', 'field_name'],
                'unique_together': {('section', 'field_name', 'language')},
            },
        ),
    ]
