# Generated by Django 5.2.6 on 2025-10-03 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_comprehensive_cms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Nom technique du champ (ex: name, email)', max_length=100, unique=True, verbose_name='Nom du champ')),
                ('field_label', models.CharField(help_text="Label affiché à l'utilisateur", max_length=200, verbose_name='Label affiché')),
                ('field_type', models.CharField(choices=[('text', 'Texte'), ('email', 'Email'), ('textarea', 'Zone de texte'), ('select', 'Liste déroulante'), ('checkbox', 'Case à cocher'), ('radio', 'Boutons radio'), ('number', 'Nombre'), ('phone', 'Téléphone'), ('url', 'URL'), ('date', 'Date')], default='text', max_length=20, verbose_name='Type de champ')),
                ('field_placeholder', models.CharField(blank=True, help_text="Texte d'aide dans le champ", max_length=200, verbose_name='Placeholder')),
                ('is_required', models.BooleanField(default=False, verbose_name='Champ obligatoire')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Visible')),
                ('options', models.JSONField(blank=True, default=list, help_text='Liste des options pour select/checkbox/radio', verbose_name='Options')),
                ('validation_pattern', models.CharField(blank=True, help_text='Expression régulière pour validation', max_length=200, verbose_name='Pattern de validation')),
                ('validation_message', models.CharField(blank=True, max_length=200, verbose_name='Message de validation')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('css_classes', models.CharField(blank=True, max_length=200, verbose_name='Classes CSS')),
                ('help_text', models.TextField(blank=True, help_text="Texte d'aide sous le champ", verbose_name="Texte d'aide")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Champ de contact',
                'verbose_name_plural': 'Champs de contact',
                'ordering': ['order', 'field_label'],
            },
        ),
    ]
