# Generated by Django 5.2.6 on 2025-10-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_contactfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de contact (alternatif)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact (alternatif)'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='discord_url',
            field=models.URLField(blank=True, verbose_name='URL Discord'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='URL Facebook'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='linkedin_url',
            field=models.URLField(blank=True, verbose_name='URL LinkedIn'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='URL Telegram'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='twitter_url',
            field=models.URLField(blank=True, verbose_name='URL Twitter'),
        ),
    ]
