# Generated by Django 5.2.6 on 2025-10-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_globalsettings_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='business_hours',
            field=models.CharField(blank=True, max_length=100, verbose_name="Horaires d'ouverture"),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='contact_title',
            field=models.CharField(default='Plusieurs façons de nous joindre', max_length=200, verbose_name='Titre de la section contact'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='support_description',
            field=models.CharField(default='24/7 Support', max_length=200, verbose_name='Description du support'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='telegram_support',
            field=models.CharField(blank=True, max_length=100, verbose_name='Support Telegram'),
        ),
    ]
