# Generated by Django 5.2.6 on 2025-10-03 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_globalsettings_business_hours_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name="Nom de l'auteur")),
                ('author_email', models.EmailField(max_length=254, verbose_name="Email de l'auteur")),
                ('author_phone', models.CharField(blank=True, max_length=20, verbose_name="Téléphone de l'auteur")),
                ('service_name', models.CharField(max_length=200, verbose_name='Nom du service')),
                ('service_type', models.CharField(help_text='Formation, Signal, Gestion de compte, etc.', max_length=50, verbose_name='Type de service')),
                ('title', models.CharField(max_length=200, verbose_name="Titre de l'avis")),
                ('content', models.TextField(verbose_name="Contenu de l'avis")),
                ('rating', models.PositiveIntegerField(default=5, help_text='Note sur 5 étoiles', verbose_name='Note')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('archived', 'Archivé')], default='pending', max_length=20, verbose_name='Statut')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Mise en avant')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approuvé le')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Approuvé par')),
            ],
            options={
                'verbose_name': 'Avis Client',
                'verbose_name_plural': 'Avis Clients',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
