# Generated by Django 5.2.6 on 2025-10-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='metadata',
            field=models.JSONField(blank=True, null=True, verbose_name='Métadonnées'),
        ),
    ]
