# Generated by Django 5.2.6 on 2025-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_offer_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='color_theme',
            field=models.CharField(choices=[('gold', 'Gold'), ('black', 'Black'), ('white', 'White')], default='gold', max_length=20, verbose_name='Couleur'),
        ),
    ]
