# Generated by Django 5.2.6 on 2025-10-07 08:47

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_offer_color_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du modèle', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du modèle')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Taux de TVA par défaut', max_digits=5)),
                ('default_payment_terms', models.IntegerField(default=30, help_text='Délai de paiement par défaut (jours)')),
                ('template_items', models.JSONField(default=list, help_text='Articles par défaut du modèle')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Modèle de facture',
                'verbose_name_plural': 'Modèles de facture',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(help_text='Numéro de facture séquentiel (CT-XXXXX)', max_length=20, unique=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('overdue', 'En retard')], default='draft', help_text='Statut de la facture', max_length=20)),
                ('issue_date', models.DateField(help_text="Date d'émission de la facture")),
                ('due_date', models.DateField(help_text="Date d'échéance de paiement")),
                ('payment_date', models.DateField(blank=True, help_text='Date de paiement effectif', null=True)),
                ('subtotal_ht', models.DecimalField(decimal_places=2, help_text='Montant HT', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('20.00'), help_text='Taux de TVA (%)', max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, help_text='Montant de la TVA', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_ttc', models.DecimalField(decimal_places=2, help_text='Montant TTC', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'Virement bancaire'), ('card', 'Carte bancaire'), ('paypal', 'PayPal'), ('crypto', 'Cryptomonnaie'), ('other', 'Autre')], help_text='Méthode de paiement utilisée', max_length=20, null=True)),
                ('transaction_reference', models.CharField(blank=True, help_text='Référence de transaction (obligatoire pour validation)', max_length=100, null=True)),
                ('company_name', models.CharField(default='Calmness Trading', help_text="Nom de l'entreprise", max_length=200)),
                ('company_address', models.TextField(default='123 Rue du Trading\n75001 Paris\nFrance', help_text="Adresse de l'entreprise")),
                ('company_siret', models.CharField(default='12345678901234', help_text='Numéro SIRET', max_length=14)),
                ('company_vat_number', models.CharField(default='FR12345678901', help_text='Numéro de TVA intracommunautaire', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes additionnelles sur la facture')),
                ('terms_conditions', models.TextField(default="Paiement à 30 jours. En cas de retard, des pénalités de 3 fois le taux d'intérêt légal seront appliquées.", help_text='Conditions générales de vente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Utilisateur ayant créé la facture', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(help_text='Client facturé', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Description de l'article ou service", max_length=200)),
                ('detailed_description', models.TextField(blank=True, help_text='Description détaillée')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Quantité', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit_price_ht', models.DecimalField(decimal_places=2, help_text='Prix unitaire HT', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_ht', models.DecimalField(decimal_places=2, help_text='Total HT de la ligne', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(help_text='Facture parente', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='payments.invoice')),
            ],
            options={
                'verbose_name': 'Article de facture',
                'verbose_name_plural': 'Articles de facture',
                'ordering': ['created_at'],
            },
        ),
    ]
