# Generated by Django 5.2.6 on 2025-10-08 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_add_invoice_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingpayment',
            name='transaction_id',
            field=models.CharField(blank=True, help_text="ID fourni par l'utilisateur après paiement", max_length=255, verbose_name='ID de Transaction'),
        ),
        migrations.AddField(
            model_name='pendingpayment',
            name='user_info',
            field=models.JSONField(blank=True, default=dict, help_text='Nom, email, téléphone, telegram, whatsapp, discord', verbose_name='Informations utilisateur'),
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='contact_info',
            field=models.CharField(blank=True, help_text='Pseudo Telegram/Discord, numéro WhatsApp, etc.', max_length=255, verbose_name='Info de contact'),
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='contact_method',
            field=models.CharField(blank=True, choices=[('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('discord', 'Discord'), ('email', 'Email')], max_length=50, verbose_name='Méthode de contact'),
        ),
        migrations.AlterField(
            model_name='pendingpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('contacted', 'Client contacté'), ('transaction_submitted', 'Transaction soumise'), ('verified', 'Transaction vérifiée'), ('confirmed', 'Confirmé'), ('cancelled', 'Annulé')], default='pending', max_length=50, verbose_name='Statut'),
        ),
    ]
