# Generated by Django 5.2.6 on 2025-10-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_pendingpayment_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='duration_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée (heures)'),
        ),
        migrations.AddField(
            model_name='offer',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée (minutes)'),
        ),
    ]
