import { useLanguage } from "@/contexts/LanguageContext";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";
import { MessageCircle, Phone, Mail } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EditableLayout } from "@/components/cms/EditableLayout";

const FAQ = () => {
  const { t } = useLanguage();

  const faqs = [
    {
      id: "1",
      question: {
        fr: "Comment fonctionnent les signaux de trading ?",
        en: "How do trading signals work?"
      },
      answer: {
        fr: "Nos signaux sont générés par des experts certifiés et envoyés directement sur Telegram. Chaque signal contient le point d'entrée, les objectifs de profit et le stop loss recommandés.",
        en: "Our signals are generated by certified experts and sent directly on Telegram. Each signal contains the entry point, profit targets and recommended stop loss."
      }
    },
    {
      id: "2",
      question: {
        fr: "Puis-je annuler mon abonnement à tout moment ?",
        en: "Can I cancel my subscription at any time?"
      },
      answer: {
        fr: "Oui, vous pouvez annuler votre abonnement à tout moment. Vous conserverez l'accès jusqu'à la fin de votre période de facturation en cours.",
        en: "Yes, you can cancel your subscription at any time. You will retain access until the end of your current billing period."
      }
    },
    {
      id: "3",
      question: {
        fr: "Comment fonctionne l'intégration Telegram ?",
        en: "How does Telegram integration work?"
      },
      answer: {
        fr: "Dès votre souscription, vous êtes automatiquement ajouté au groupe Telegram correspondant à votre plan. En fin d'abonnement, l'accès est automatiquement révoqué.",
        en: "Upon subscription, you are automatically added to the Telegram group corresponding to your plan. At the end of subscription, access is automatically revoked."
      }
    },
    {
      id: "4",
      question: {
        fr: "Quel est le niveau requis pour suivre les formations ?",
        en: "What level is required to follow the training?"
      },
      answer: {
        fr: "Nos formations s'adaptent à tous les niveaux, du débutant complet au trader expérimenté. Chaque module indique clairement le niveau requis.",
        en: "Our training adapts to all levels, from complete beginner to experienced trader. Each module clearly indicates the required level."
      }
    },
    {
      id: "5",
      question: {
        fr: "Y a-t-il une garantie de remboursement ?",
        en: "Is there a money-back guarantee?"
      },
      answer: {
        fr: "Nous offrons une garantie satisfait ou remboursé de 30 jours sur tous nos plans d'abonnement.",
        en: "We offer a 30-day money-back guarantee on all our subscription plans."
      }
    },
    {
      id: "6",
      question: {
        fr: "Comment puis-je contacter le support ?",
        en: "How can I contact support?"
      },
      answer: {
        fr: "Notre équipe support est disponible 24/7 via Telegram, email ou téléphone. Vous recevrez une réponse dans les 2 heures ouvrées.",
        en: "Our support team is available 24/7 via Telegram, email or phone. You will receive a response within 2 business hours."
      }
    },
    {
      id: "7",
      question: {
        fr: "Quels marchés couvrez-vous ?",
        en: "What markets do you cover?"
      },
      answer: {
        fr: "Nous couvrons le Forex, les indices, les matières premières et les cryptomonnaies avec des analyses techniques approfondies pour chaque marché.",
        en: "We cover Forex, indices, commodities and cryptocurrencies with in-depth technical analysis for each market."
      }
    },
    {
      id: "8",
      question: {
        fr: "Les formations sont-elles certifiées ?",
        en: "Are the trainings certified?"
      },
      answer: {
        fr: "Oui, toutes nos formations sont dispensées par des traders professionnels certifiés avec plus de 10 ans d'expérience sur les marchés.",
        en: "Yes, all our training is provided by certified professional traders with over 10 years of experience in the markets."
      }
    }
  ];

  const translations = {
    'faq.title': { fr: 'Questions Fréquentes', en: 'Frequently Asked Questions' },
    'faq.subtitle': { fr: 'Trouvez rapidement les réponses à vos questions', en: 'Quickly find answers to your questions' },
    'faq.contact.title': { fr: 'Vous ne trouvez pas votre réponse ?', en: "Can't find your answer?" },
    'faq.contact.subtitle': { fr: 'Notre équipe support est là pour vous aider', en: 'Our support team is here to help you' },
    'faq.contact.telegram': { fr: 'Support Telegram', en: 'Telegram Support' },
    'faq.contact.phone': { fr: 'Assistance Téléphone', en: 'Phone Support' },
    'faq.contact.email': { fr: 'Support Email', en: 'Email Support' }
  };

  const t2 = (key: string): string => {
    return translations[key]?.[useLanguage().language] || key;
  };

  return (
    <EditableLayout pageSlug="faq">
      <div className="min-h-screen bg-background">
        <Header />
        <main className="pt-20">
        {/* Hero Section */}
        <section className="py-20 bg-gradient-to-br from-primary/10 via-transparent to-secondary/10">
          <div className="container mx-auto px-4">
            <div className="text-center max-w-4xl mx-auto">
              <h1 className="text-4xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
                {t2('faq.title')}
              </h1>
              <p className="text-xl text-muted-foreground mb-8">
                {t2('faq.subtitle')}
              </p>
            </div>
          </div>
        </section>

        {/* FAQ Section */}
        <section className="py-20">
          <div className="container mx-auto px-4">
            <div className="max-w-4xl mx-auto">
              <Accordion type="single" collapsible className="space-y-4">
                {faqs.map((faq) => (
                  <AccordionItem key={faq.id} value={faq.id} className="border rounded-lg px-6">
                    <AccordionTrigger className="text-left hover:no-underline py-6">
                      <span className="font-semibold">
                        {faq.question[useLanguage().language]}
                      </span>
                    </AccordionTrigger>
                    <AccordionContent className="pb-6 text-muted-foreground leading-relaxed">
                      {faq.answer[useLanguage().language]}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </div>
          </div>
        </section>

        {/* Contact Support Section */}
        <section className="py-20 bg-muted/50">
          <div className="container mx-auto px-4 text-center">
            <h2 className="text-3xl font-bold mb-4">{t2('faq.contact.title')}</h2>
            <p className="text-muted-foreground mb-12 max-w-2xl mx-auto">
              {t2('faq.contact.subtitle')}
            </p>
            
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-4xl mx-auto">
              <div className="text-center">
                <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <MessageCircle className="w-8 h-8 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">{t2('faq.contact.telegram')}</h3>
                <p className="text-muted-foreground mb-4">24/7</p>
                <Button variant="outline">@CalmnessFi_Support</Button>
              </div>
              
              <div className="text-center">
                <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Phone className="w-8 h-8 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">{t2('faq.contact.phone')}</h3>
                <p className="text-muted-foreground mb-4">Lun-Ven 9h-18h</p>
                <Button variant="outline">+33 1 23 45 67 89</Button>
              </div>
              
              <div className="text-center">
                <div className="w-16 h-16 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-4">
                  <Mail className="w-8 h-8 text-primary" />
                </div>
                <h3 className="font-semibold mb-2">{t2('faq.contact.email')}</h3>
                <p className="text-muted-foreground mb-4">Réponse sous 2h</p>
                <Button variant="outline">support@calmnessfi.com</Button>
              </div>
            </div>
          </div>
        </section>
        </main>
        <Footer />
      </div>
    </EditableLayout>
  );
};

export default FAQ;